In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from sklearn import metrics

In [2]:
iris_df = sns.load_dataset('iris')

In [3]:
dt =tree.DecisionTreeClassifier()

In [4]:
iris_X = iris_df.drop(columns=['species'])
iris_y = iris_df['species']

In [5]:
cross_val_score(dt,iris_X,iris_y,)

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [6]:
np.mean(cross_val_score(dt,iris_X,iris_y,))

0.9666666666666668

In [7]:
cross_val_score(dt,iris_X,iris_y,cv=10)

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 0.93333333, 1.        , 1.        ])

In [8]:
np.mean(cross_val_score(dt,iris_X,iris_y,))

0.9600000000000002

In [9]:
km = KMeans(n_clusters=3)

In [10]:
cross_val_score(km,iris_X,)

array([ -9.062     , -14.93195873, -18.93234207, -23.70894258,
       -19.55457726])